server:
  port:8077
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-port: 8761

    service-url:
      defaultZone: http://localhost:8761/eureka/
